export const SCREENS = {
  SPLASH: 'splash',
  LOGIN: 'login',
  FORGOT_PASSWORD: 'forgotpassword',
  CONTACT_SUPPORT: 'contactsupport',
  PROFILE_OPTION: 'profileoption',
  MAIN: 'main', // Keep for backward compatibility
  TEACHER_MAIN: 'teachermain',
  STUDENT_MAIN: 'studentmain',
  DASHBOARD: 'dashboard', // Inside the drawer
  STUDENT_DASHBOARD: 'studentdashboard',
  PROFILE: 'profile',
  ATTENDANCE: 'attendance',
  ATTENDANCE_HUB: 'attendancehub',
  STUDENT_ATTENDANCE_HUB: 'studentattendancehub',
  STAFF_ATTENDANCE: 'staffattendance',
  STUDENT_ATTENDANCE: 'studentattendance',
  SCHEDULE: 'schedule',
  NOTIFICATIONS: 'notifications',
  SETTINGS: 'settings',
  SUPPORT: 'support',
  TERMS_CONDITIONS: 'termsconditions',
  PRIVACY_POLICY: 'privacypolicy',
  FAQ: 'faq',
  FULL_SCHEDULE: 'fullschedule',
  LEAVE_MANAGEMENT: 'leavemanagement',
  MY_LEAVES: 'myleaves',
  NOTICE_DETAIL: 'noticedetail',
  LEAVE_DETAIL: 'leavedetail',
  EVENT_HUB: 'eventhub',
  GALLERY: 'gallery',
  ADD_EVENT: 'addevent',
  EVENT_DETAIL: 'eventdetail',
  MEETING_DETAIL: 'meetingdetail',
  APPLY_LEAVE: 'applyleave',
  EVENT_CALENDAR: 'eventcalendar',
  ALL_NOTICES: 'allnotices',
  HOMEWORK_LIST: 'homeworklist',
  ADD_HOMEWORK: 'addhomework',
  HOMEWORK_DETAIL: 'homeworkdetail',
  PARENT_PROFILES: 'parentprofiles',
  STUDENT_HUB: 'studenthub',
  HOLIDAY_LIST: 'holidaylist',
  STUDENT_LIST: 'studentlist',
  MANAGE_STUDENT: 'managestudent',
  FEE_DASHBOARD: 'feedashboard',
  COLLECT_FEE: 'collectfee',
  STUDENT_FEES: 'studentfees',
  STUDENT_FEE_DETAIL: 'studentfeedetail',
  SYLLABUS_LIST: 'syllabuslist',
  SYLLABUS_DETAIL: 'syllabusdetail',
  DOWNLOADS: 'downloads',
  EXAMS_LIST: 'examslist',
  EXAMS_DETAIL: 'examsdetail',
  EXAMS_MARKS_ENTRY: 'examsmarksentry',
  MY_SALARY: 'mysalary',
  MY_GRIEVANCES: 'mygrievances',
  SUBMIT_GRIEVANCE: 'submitgrievance',
  GRIEVANCE_DETAIL: 'grievancedetail',
} as const;

export const TEACHER_MENU = [
  { name: SCREENS.DASHBOARD, icon: 'home-variant-outline', label: 'Dashboard' },
  { name: SCREENS.PROFILE, icon: 'account-outline', label: 'My Profile' },
  { name: SCREENS.MY_SALARY, icon: 'receipt-text-outline', label: 'My Salary' },
  { name: SCREENS.STUDENT_HUB, icon: 'account-group-outline', label: 'Manage Students' },
  { name: SCREENS.ATTENDANCE_HUB, icon: 'calendar-check-outline', label: 'Attendance Hub' },
  { name: SCREENS.FEE_DASHBOARD, icon: 'cash-register', label: 'Fee Records' },
  { name: SCREENS.EVENT_HUB, icon: 'calendar-star-outline', label: 'Event Hub' },
  { name: SCREENS.HOLIDAY_LIST, icon: 'calendar-heart-outline', label: 'Holidays' },
  { name: SCREENS.HOMEWORK_LIST, icon: 'book-open-variant-outline', label: 'Homework' },
  { name: SCREENS.SYLLABUS_LIST, icon: 'book-education-outline', label: 'Syllabus' },
  { name: SCREENS.EXAMS_LIST, icon: 'file-document-edit-outline', label: 'Exams' },
  { name: SCREENS.MY_GRIEVANCES, icon: 'message-alert-outline', label: 'My Grievances' },
] as const;

export const STUDENT_MENU = [
  { name: SCREENS.DASHBOARD, icon: 'home-variant-outline', label: 'Dashboard' },
  { name: SCREENS.PROFILE, icon: 'account-outline', label: 'My Profile' },
  { name: SCREENS.STUDENT_FEES, icon: 'credit-card-outline', label: 'Fees' },
  { name: SCREENS.STUDENT_ATTENDANCE_HUB, icon: 'calendar-check-outline', label: 'Attendance Hub' },
  { name: SCREENS.EVENT_HUB, icon: 'calendar-star-outline', label: 'Event Hub' },
  { name: SCREENS.HOLIDAY_LIST, icon: 'calendar-heart-outline', label: 'Holidays' },
  { name: SCREENS.HOMEWORK_LIST, icon: 'book-open-variant-outline', label: 'Homework' },
  { name: SCREENS.SYLLABUS_LIST, icon: 'book-education-outline', label: 'Syllabus' },
  { name: SCREENS.EXAMS_LIST, icon: 'file-document-edit-outline', label: 'Exams' },
  { name: SCREENS.MY_GRIEVANCES, icon: 'message-alert-outline', label: 'My Grievances' },
] as const;

export const PARENT_MENU = [
  { name: SCREENS.DASHBOARD, icon: 'home-variant-outline', label: 'Dashboard' },
  { name: SCREENS.PARENT_PROFILES, icon: 'account-multiple-outline', label: 'Profiles' },
  { name: SCREENS.PROFILE, icon: 'account-outline', label: 'Child Profile' },
  { name: SCREENS.STUDENT_FEES, icon: 'credit-card-outline', label: 'Fees' },
  { name: SCREENS.STUDENT_ATTENDANCE_HUB, icon: 'calendar-check-outline', label: 'Attendance Hub' },
  { name: SCREENS.EVENT_HUB, icon: 'calendar-star-outline', label: 'Event Hub' },
  { name: SCREENS.HOLIDAY_LIST, icon: 'calendar-heart-outline', label: 'Holidays' },
  { name: SCREENS.HOMEWORK_LIST, icon: 'book-open-variant-outline', label: 'Homework' },
  { name: SCREENS.SYLLABUS_LIST, icon: 'book-education-outline', label: 'Syllabus' },
  { name: SCREENS.EXAMS_LIST, icon: 'file-document-edit-outline', label: 'Exams' },
] as const;

export type ScreenName = typeof SCREENS[keyof typeof SCREENS];
