import { StyleSheet } from 'react-native';
import { Theme } from '../../../constants/theme';
import { getShadow } from '../../../utils/shadow';
import { rfValue } from '../../../utils/responsive';
import { FontFamily } from '../../../utils/typography';

export const contactSupportStyles = (theme: Theme, insets: any) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
  },
  topSection: {
    flexGrow: 1,
    height: 250,
    backgroundColor: theme.colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: insets.top,
    overflow: 'hidden',
  },
  backButton: {
    position: 'absolute',
    top: insets.top + 10,
    left: 20,
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 100,
  },
  bgCircle1: {
    position: 'absolute',
    width: 300,
    height: 300,
    borderRadius: 150,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    top: -120,
    right: -100,
  },
  bgCircle2: {
    position: 'absolute',
    width: 150,
    height: 150,
    borderRadius: 75,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    bottom: 20,
    left: -30,
  },
  bgCircle3: {
    position: 'absolute',
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    top: 40,
    left: 60,
  },
  bgCircle4: {
    position: 'absolute',
    width: 250,
    height: 250,
    borderRadius: 125,
    backgroundColor: 'rgba(0, 0, 0, 0.03)',
    top: -100,
    left: -80,
  },
  bgCircle5: {
    position: 'absolute',
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: 'rgba(255, 255, 255, 0.12)',
    bottom: -30,
    right: 20,
  },
  bgCircle6: {
    position: 'absolute',
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: 'rgba(0, 0, 0, 0.04)',
    right: 40,
    top: 100,
  },
  logoCircle: {
    width: 110,
    height: 110,
    borderRadius: 55,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.6)',
  },
  brandName: {
    fontFamily: FontFamily.black,
    fontSize: rfValue(24),
    color: '#FFFFFF',
    marginTop: 12,
  },
  bottomSection: {
    flex: 1,
    paddingHorizontal: 28,
    backgroundColor: theme.colors.surface,
    borderTopLeftRadius: 36,
    borderTopRightRadius: 36,
    marginTop: -36,
    paddingTop: 32,
    ...getShadow(5, '#000', 0.1),
  },
  welcomeTitle: {
    fontFamily: FontFamily.black,
    fontSize: rfValue(28),
    color: theme.colors.text,
  },
  welcomeSub: {
    fontFamily: FontFamily.body,
    fontSize: rfValue(15),
    color: theme.colors.textSecondary,
    marginTop: 4,
    marginBottom: 28,
  },
  contactContainer: {
    flexDirection: 'row',
    gap: 12,
  },
  contactCard: {
    flex: 1,
    backgroundColor: theme.colors.surface,
    borderRadius: 24,
    paddingVertical: 28,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: theme.colors.cardBorder,
    ...getShadow(10, theme.colors.primary, 0.08),
  },
  iconContainer: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: theme.colors.vegBackground,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  contactLabel: {
    fontFamily: FontFamily.heading,
    fontSize: rfValue(15),
    color: theme.colors.text,
    marginTop: 4,
    marginBottom: 4,
  },
  contactValue: {
    fontFamily: FontFamily.body,
    fontSize: rfValue(13),
    color: theme.colors.textSecondary,
    textAlign: 'center',
  },
});
