import { StyleSheet } from 'react-native';
import { Theme } from '../../constants/theme';
import { rfValue } from '../../utils/responsive';
import { FontFamily } from '../../utils/typography';

export const customDrawerStyles = (theme: Theme, insets: any) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.colors.surface,
    },
    // Header Styling
    header: {
      paddingTop: Math.max(insets.top + 16, 36),
      paddingHorizontal: 20,
      paddingBottom: 20,
      backgroundColor: theme.colors.primary,
      borderBottomLeftRadius: 24,
      borderBottomRightRadius: 24,
      shadowColor: theme.colors.shadowColor,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 10,
      elevation: 6,
    },
    topBrandRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 18,
    },
    logo: {
      width: 120,
      height: 34,
    },
    constituencyBadge: {
      backgroundColor: 'rgba(255, 255, 255, 0.18)',
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.25)',
    },
    constituencyText: {
      fontFamily: FontFamily.bodyBold,
      fontSize: rfValue(10),
      color: '#FFFFFF',
      letterSpacing: 0.5,
    },
    profileSection: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    avatarContainer: {
      width: 56,
      height: 56,
      borderWidth: 1,
      borderRadius: 28,
      position: 'relative',
      borderColor: 'rgba(255, 255, 255, 0.4)',
      backgroundColor: 'rgba(255, 255, 255, 0.2)',
    },
    avatar: {
      width: '100%',
      height: '100%',
      borderRadius: 26,
    },
    statusDot: {
      position: 'absolute',
      bottom: 1,
      right: 1,
      width: 12,
      height: 12,
      borderWidth: 2,
      borderRadius: 6,
      backgroundColor: '#00ffaaff',
      borderColor: theme.colors.primary,
    },
    userInfo: {
      marginLeft: 14,
      flex: 1,
    },
    userName: {
      fontFamily: FontFamily.black,
      fontSize: rfValue(16),
      color: '#FFFFFF',
      letterSpacing: -0.3,
    },
    rolePill: {
      alignSelf: 'flex-start',
      backgroundColor: 'rgba(255, 255, 255, 0.2)',
      paddingHorizontal: 8,
      paddingVertical: 2,
      borderRadius: 12,
      marginTop: 4,
    },
    userRole: {
      fontFamily: FontFamily.bodyBold,
      fontSize: rfValue(11),
      color: '#FFFFFF',
      letterSpacing: 0.5,
      textTransform: 'uppercase',
    },
    assignedArea: {
      fontFamily: FontFamily.body,
      fontSize: rfValue(11),
      color: 'rgba(255, 255, 255, 0.75)',
      marginTop: 3,
    },

    // Content Scroll View
    drawerContent: {
      paddingHorizontal: 14,
      paddingBottom: 24,
    },
    categoryHeader: {
      marginTop: 14,
      marginBottom: 8,
      paddingHorizontal: 10,
    },
    categoryHeaderText: {
      fontFamily: FontFamily.bodyBold,
      fontSize: rfValue(12),
      color: theme.colors.textSecondary,
      letterSpacing: 1.2,
      textTransform: 'uppercase',
      opacity: 0.8,
    },
    drawerItem: {
      position: 'relative',
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 10,
      paddingHorizontal: 14,
      borderRadius: 14,
      marginBottom: 4,
      overflow: 'hidden',
    },
    drawerItemActive: {
      borderLeftWidth: 5,
      borderLeftColor: theme.colors.primary,
      backgroundColor: theme.colors.vegBackground || 'rgba(30, 64, 175, 0.08)',
    },
    drawerItemIcon: {
      width: 35,
      height: 35,
      marginRight: 12,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.inputBackground,
    },
    drawerItemIconActive: {
      backgroundColor: 'rgba(30, 64, 175, 0.08)',
    },
    drawerItemText: {
      flex: 1,
      fontSize: rfValue(16),
      color: theme.colors.text,
      fontFamily: FontFamily.bodyBold,
    },
    drawerItemTextActive: {
      color: theme.colors.primary,
      fontFamily: FontFamily.black,
    },
    badgeContainer: {
      backgroundColor: theme.colors.primary,
      paddingHorizontal: 8,
      paddingVertical: 2,
      borderRadius: 10,
    },
    badgeText: {
      fontFamily: FontFamily.bodyBold,
      fontSize: rfValue(10),
      color: '#FFFFFF',
    },

    // Footer Controls
    footer: {
      paddingHorizontal: 16,
      paddingTop: 12,
      paddingBottom: Math.max(insets.bottom + 12, 20),
      borderTopWidth: 1,
      borderTopColor: theme.colors.border,
      backgroundColor: theme.colors.surface,
    },
    quickActionRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 10,
    },
    themeToggleBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 10,
      paddingHorizontal: 14,
      borderRadius: 12,
      backgroundColor: theme.colors.inputBackground,
      flex: 1,
      marginRight: 10,
    },
    themeToggleText: {
      marginLeft: 8,
      fontFamily: FontFamily.bodyBold,
      fontSize: rfValue(13),
      color: theme.colors.text,
    },
    logoutButton: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 10,
      paddingHorizontal: 14,
      borderRadius: 12,
      backgroundColor: 'rgba(239, 68, 68, 0.08)',
    },
    logoutText: {
      fontFamily: FontFamily.bodyBold,
      fontSize: rfValue(13),
      color: theme.colors.error,
      marginLeft: 6,
    },
    version: {
      fontFamily: FontFamily.body,
      fontSize: rfValue(11),
      color: theme.colors.textSecondary,
      textAlign: 'center',
      marginTop: 8,
      opacity: 0.7,
    },

    // Modal Styling
    modalCard: {
      width: '88%',
      maxWidth: 340,
      padding: 22,
      borderRadius: 20,
      alignItems: 'center',
    },
    modalIconContainer: {
      width: 56,
      height: 56,
      borderRadius: 28,
      backgroundColor: 'rgba(239, 68, 68, 0.1)',
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 16,
    },
    modalTitle: {
      fontFamily: FontFamily.black,
      fontSize: rfValue(18),
      color: theme.colors.text,
      marginBottom: 6,
      textAlign: 'center',
    },
    modalDescription: {
      fontFamily: FontFamily.body,
      fontSize: rfValue(13),
      color: theme.colors.textSecondary,
      textAlign: 'center',
      marginBottom: 22,
      lineHeight: 18,
    },
    modalButtonRow: {
      flexDirection: 'row',
      width: '100%',
      gap: 12,
    },
    cancelBtn: {
      flex: 1,
      paddingVertical: 12,
      borderRadius: 12,
      backgroundColor: theme.colors.inputBackground,
      alignItems: 'center',
    },
    cancelBtnText: {
      fontFamily: FontFamily.bodyBold,
      fontSize: rfValue(14),
      color: theme.colors.text,
    },
    confirmBtn: {
      flex: 1,
      paddingVertical: 12,
      borderRadius: 12,
      backgroundColor: theme.colors.error,
      alignItems: 'center',
    },
    confirmBtnText: {
      fontFamily: FontFamily.bodyBold,
      fontSize: rfValue(14),
      color: '#FFFFFF',
    },
  });
