import { logger } from '../utils/logger';
import { Request, Response } from 'express';
import { ApiError } from '../utils/apiError';
import { attachFileUrls } from '../utils/fileUrl';
import { ApiResponse } from '../utils/apiResponse';
import { sendWelcomeEmail } from '../utils/mailer';
import { asyncHandler } from '../utils/asyncHandler';
import { RoleQueries } from '../queries/role.queries';
import { authService } from '../services/auth.service';
import { TenantQueries } from '../queries/tenant.queries';
import { generateTenantPassword } from '../utils/password';
import { getTenantDbPool } from '../utils/tenantDbProvisioner';
import { tenantProvisioningService } from '../services/tenantProvisioning.service';

export class TenantController {
  /**
   * Provision a new tenant user account (Phase 1)
   */
  provisionTenantUser = asyncHandler(async (req: Request, res: Response): Promise<void> => {
    const { name, email, mobile, organizationName, pcIds, acIds, tenantRoleId, avatar } = req.body;

    if (!name || !email || !mobile || !organizationName) {
      throw new ApiError(400, 'Name, email, mobile, and organization name are required');
    }

    if (!acIds || !Array.isArray(acIds) || acIds.length === 0) {
      throw new ApiError(400, 'At least one Assembly Constituency (AC) must be selected');
    }

    // Determine target tenant role package: if not provided, auto-assign default role package
    let assignedRoleId = tenantRoleId || null;
    if (!assignedRoleId) {
      const defaultRole = await RoleQueries.getDefaultTenantRole();
      if (defaultRole) {
        assignedRoleId = defaultRole.id;
      }
    }

    // Generate auto password (e.g. Rajesh3210@)
    const rawPassword = generateTenantPassword(name, mobile);

    // Derive clean tenant database name: ranniti_tenant_[firstname]_[last4phone]
    const cleanFirstName = name.trim().split(' ')[0].toLowerCase().replace(/[^a-z0-9]/g, '');
    const cleanDigits = mobile.replace(/\D/g, '').slice(-4);
    const tenantDbName = `ranniti_tenant_${cleanFirstName}_${cleanDigits}`;

    // 1. Register user in admin_users with role='tenant_admin' and role_name='Tenant Admin'
    const user = await authService.registerUser({
      name: name.trim(),
      email: email.trim().toLowerCase(),
      mobile: mobile.trim(),
      password: rawPassword,
      role: 'tenant_admin',
      roleName: 'Tenant Admin',
      avatar: avatar || null,
    });

    // 2. Create tenant_assignments record
    const assignment = await TenantQueries.createTenantAssignment({
      userId: user.id,
      organizationName: organizationName.trim(),
      tenantDbName,
      pcIds: Array.isArray(pcIds) ? pcIds : [],
      acIds: Array.isArray(acIds) ? acIds : [],
      tenantRoleId: assignedRoleId,
    });

    // 3. Update tenant_db_name on admin_users row
    await TenantQueries.updateUserTenantDbName(user.id, tenantDbName);

    // 4. Trigger background async tenant database creation, schema init, & voter data copy (non-blocking)
    const acList = Array.isArray(acIds) ? acIds : [];
    const pcList = Array.isArray(pcIds) ? pcIds : [];
    tenantProvisioningService
      .provisionTenantDataAsync(user.id, tenantDbName, acList, pcList)
      .catch((err) => {
        logger.error(`[TenantController] Background provisioning error for user '${user.id}':`, err);
      });

    // 5. Send Welcome Email asynchronously with login link & credentials (non-blocking)
    const loginUrl = `${process.env.APP_FRONTEND_URL || 'http://localhost:5173'}/login`;
    sendWelcomeEmail(user.email, user.name, rawPassword, loginUrl).catch((err) => {
      logger.error('Background welcome email send failed:', err);
    });

    const combinedData = {
      ...user,
      tenantDbName,
      assignment,
      autoGeneratedPassword: rawPassword, // Returned for super admin UI display/copy convenience
    };

    const formattedData = attachFileUrls(combinedData, ['avatar'], req);
    const response = ApiResponse.success(formattedData, 'Tenant user created successfully', 201);
    res.status(response.statusCode).json(response.body);
  });

  /**
   * Get all tenant users with assignment details
   */
  getAllTenantUsers = asyncHandler(async (req: Request, res: Response): Promise<void> => {
    const tenants = await TenantQueries.getAllTenantUsers();
    const formattedTenants = attachFileUrls(tenants, ['avatar'], req);
    const response = ApiResponse.success(formattedTenants, 'Tenant users retrieved successfully');
    res.status(response.statusCode).json(response.body);
  });

  /**
   * Get tenant user details by ID
   */
  getTenantUserById = asyncHandler(async (req: Request, res: Response): Promise<void> => {
    const id = req.params.id as string;
    const tenant = await TenantQueries.getTenantUserByUserId(id);
    if (!tenant) {
      throw new ApiError(404, 'Tenant user not found');
    }
    const formattedTenant = attachFileUrls(tenant, ['avatar'], req);
    const response = ApiResponse.success(formattedTenant, 'Tenant user retrieved successfully');
    res.status(response.statusCode).json(response.body);
  });

  /**
   * Get real-time tenant database provisioning status and progress metrics
   */
  getTenantProvisioningStatus = asyncHandler(async (req: Request, res: Response): Promise<void> => {
    const id = req.params.id as string;
    const tenant = await TenantQueries.getTenantUserByUserId(id);
    if (!tenant) {
      throw new ApiError(404, 'Tenant user not found');
    }
    const statusData = {
      id: tenant.id,
      tenantDbName: tenant.tenantDbName,
      provisioningStatus: tenant.provisioningStatus || 'pending',
      provisioningProgress: tenant.provisioningProgress || 0,
      totalVotersCopied: tenant.totalVotersCopied || 0,
      currentStep: tenant.currentStep || '',
      errorMessage: tenant.errorMessage || null,
      accountStatus: tenant.accountStatus || 'active',
      updatedAt: tenant.updatedAt,
    };
    const response = ApiResponse.success(statusData, 'Tenant provisioning status retrieved successfully');
    res.status(response.statusCode).json(response.body);
  });

  /**
   * Update tenant user details
   */
  updateTenantUser = asyncHandler(async (req: Request, res: Response): Promise<void> => {
    const id = req.params.id as string;
    const { name, email, mobile, organizationName, pcIds, acIds, tenantRoleId, avatar } = req.body;

    if (!name || !email || !mobile || !organizationName) {
      throw new ApiError(400, 'Name, email, mobile, and organization name are required');
    }

    const existing = await TenantQueries.getTenantUserByUserId(id);
    if (!existing) {
      throw new ApiError(404, 'Tenant user not found');
    }

    const newAcIds: string[] = Array.isArray(acIds) ? acIds : [];
    const newPcIds: string[] = Array.isArray(pcIds) ? pcIds : [];

    let addedAcIds: string[] = [];
    let removedAcIds: string[] = [];

    if (existing.tenantDbName) {
      try {
        const tenantPool = getTenantDbPool(existing.tenantDbName);
        const existingAcRes = await tenantPool.query('SELECT id FROM assembly_constituencies');
        await tenantPool.end();
        const tenantAcIds: string[] = existingAcRes.rows.map((r: any) => r.id);

        addedAcIds = newAcIds.filter((ac) => !tenantAcIds.includes(ac));
        removedAcIds = tenantAcIds.filter((ac) => !newAcIds.includes(ac));
      } catch (e) {
        const existingAcIds: string[] = Array.isArray(existing.acIds) ? existing.acIds : [];
        addedAcIds = newAcIds.filter((ac) => !existingAcIds.includes(ac));
        removedAcIds = existingAcIds.filter((ac) => !newAcIds.includes(ac));
      }
    } else {
      const existingAcIds: string[] = Array.isArray(existing.acIds) ? existing.acIds : [];
      addedAcIds = newAcIds.filter((ac) => !existingAcIds.includes(ac));
      removedAcIds = existingAcIds.filter((ac) => !newAcIds.includes(ac));
    }

    const updated = await TenantQueries.updateTenantUser(id, {
      name: name.trim(),
      email: email.trim().toLowerCase(),
      mobile: mobile.trim(),
      organizationName: organizationName.trim(),
      pcIds: newPcIds,
      acIds: newAcIds,
      tenantRoleId: tenantRoleId || null,
      avatar: avatar ?? null,
    });

    if (existing.tenantDbName) {
      // Remove voters + booths + ACs for de-scoped ACs (synchronous data safety)
      if (removedAcIds.length > 0) {
        logger.info(`[TenantController] ${removedAcIds.length} AC(s) removed for tenant '${id}' — purging scoped data...`);
        tenantProvisioningService
          .removeAcVoters(id, existing.tenantDbName, removedAcIds)
          .catch((err) => {
            logger.error(`[TenantController] AC voter removal error for tenant '${id}':`, err);
          });
      }

      // Sync voters + master data for newly added / missing ACs
      if (addedAcIds.length > 0) {
        logger.info(`[TenantController] ${addedAcIds.length} new/missing AC(s) added for tenant '${id}' — triggering incremental voter sync...`);
        tenantProvisioningService
          .syncNewAcVoters(id, existing.tenantDbName, addedAcIds, newPcIds)
          .catch((err) => {
            logger.error(`[TenantController] Incremental voter sync error for tenant '${id}':`, err);
          });
      }
    }

    const formatted = attachFileUrls(updated, ['avatar'], req);
    const response = ApiResponse.success(formatted, 'Tenant user updated successfully');
    res.status(response.statusCode).json(response.body);
  });


  /**
   * Update tenant account status (active, inactive, suspended)
   */
  updateTenantStatus = asyncHandler(async (req: Request, res: Response): Promise<void> => {
    const id = req.params.id as string;
    const { status } = req.body;

    if (!status || !['active', 'inactive', 'suspended'].includes(status)) {
      throw new ApiError(400, 'Valid status (active, inactive, suspended) is required');
    }

    const existing = await TenantQueries.getTenantUserByUserId(id);
    if (!existing) {
      throw new ApiError(404, 'Tenant user not found');
    }

    const updated = await TenantQueries.updateTenantStatus(id, status);
    const formatted = attachFileUrls(updated, ['avatar'], req);
    const response = ApiResponse.success(formatted, `Tenant user status updated to ${status}`);
    res.status(response.statusCode).json(response.body);
  });

  /**
   * Delete tenant account
   */
  deleteTenantUser = asyncHandler(async (req: Request, res: Response): Promise<void> => {
    const id = req.params.id as string;
    const existing = await TenantQueries.getTenantUserByUserId(id);
    if (!existing) {
      throw new ApiError(404, 'Tenant user not found');
    }

    await TenantQueries.deleteTenantUser(id);
    const response = ApiResponse.success({ id }, 'Tenant account deleted successfully');
    res.status(response.statusCode).json(response.body);
  });
}

export const tenantController = new TenantController();

