import { Pool } from 'pg';
import { logger } from '../../utils/logger';
import { Request, Response } from 'express';
import { ApiError } from '../../utils/apiError';
import { hashPassword } from '../../utils/password';
import { attachFileUrls } from '../../utils/fileUrl';
import { ApiResponse } from '../../utils/apiResponse';
import { sendWelcomeEmail } from '../../utils/mailer';
import { asyncHandler } from '../../utils/asyncHandler';
import { RoleQueries } from '../../queries/role.queries';
import { query as masterQuery } from '../../queries/dbPool';
import { TenantQueries } from '../../queries/tenant.queries';
import { generateTenantPassword } from '../../utils/password';
import { getTenantDbPool } from '../../utils/tenantDbProvisioner';
import { tenantProvisioningService } from '../../provisioning/services/tenantProvisioning.service';

export class TenantController {
  /**
   * Provision a new tenant account — inserts directly into tenants table.
   */
  provisionTenantUser = asyncHandler(async (req: Request, res: Response): Promise<void> => {
    const { name, email, mobile, organizationName, pcIds, acIds, tenantRoleId, avatar } = req.body;

    if (!name || !email || !mobile || !organizationName) {
      throw new ApiError(400, 'Name, email, mobile, and organization name are required');
    }

    let resolvedAcIds: string[] = Array.isArray(acIds) ? [...acIds] : [];
    const resolvedPcIds: string[] = Array.isArray(pcIds) ? [...pcIds] : [];

    // Auto-resolve child ACs if only PCs are provided
    if (resolvedAcIds.length === 0 && resolvedPcIds.length > 0) {
      const acRes = await masterQuery(
        'SELECT id FROM assembly_constituencies WHERE pc_id = ANY($1)',
        [resolvedPcIds]
      );
      resolvedAcIds = acRes.rows.map((r: any) => r.id);
    } else if (resolvedPcIds.length === 0 && resolvedAcIds.length > 0) {
      const pcRes = await masterQuery(
        'SELECT DISTINCT pc_id FROM assembly_constituencies WHERE id = ANY($1) AND pc_id IS NOT NULL',
        [resolvedAcIds]
      );
      for (const r of pcRes.rows) {
        if (r.pc_id && !resolvedPcIds.includes(r.pc_id)) {
          resolvedPcIds.push(r.pc_id);
        }
      }
    }

    if (resolvedAcIds.length === 0) {
      throw new ApiError(400, 'At least one Assembly Constituency (AC) or Parliamentary Constituency (PC) must be selected');
    }

    // Auto-assign default role package if not specified
    let assignedRoleId = tenantRoleId || null;
    if (!assignedRoleId) {
      const defaultRole = await RoleQueries.getDefaultTenantRole();
      if (defaultRole) {
        assignedRoleId = defaultRole.id;
      }
    }

    // Generate auto password and tenant DB name
    const rawPassword = generateTenantPassword(name, mobile);
    const passwordHash = await hashPassword(rawPassword);

    const cleanFirstName = name.trim().split(' ')[0].toLowerCase().replace(/[^a-z0-9]/g, '');
    const cleanDigits = mobile.replace(/\D/g, '').slice(-4);
    const tenantDbName = `ranniti_tenant_${cleanFirstName}_${cleanDigits}`;

    // Create tenant row directly in tenants table (no admin_users involvement)
    const tenant = await TenantQueries.createTenant({
      name: name.trim(),
      email: email.trim().toLowerCase(),
      passwordHash,
      mobile: mobile.trim(),
      organizationName: organizationName.trim(),
      tenantDbName,
      pcIds: resolvedPcIds,
      acIds: resolvedAcIds,
      avatar: avatar || null,
      tenantRoleId: assignedRoleId,
    });

    // Trigger background DB creation + schema init + voter copy (non-blocking)
    tenantProvisioningService
      .provisionTenantDataAsync(tenant.id, tenantDbName, resolvedAcIds, resolvedPcIds)
      .catch((err) => {
        logger.error(`[TenantController] Background provisioning error for tenant '${tenant.id}':`, err);
      });

    // Send welcome email asynchronously
    const loginUrl = `${process.env.APP_FRONTEND_URL || 'http://localhost:5173'}/login`;
    sendWelcomeEmail(tenant.email, tenant.name, rawPassword, loginUrl).catch((err) => {
      logger.error('[TenantController] Welcome email send failed:', err);
    });

    const formattedData = attachFileUrls(
      { ...tenant, autoGeneratedPassword: rawPassword },
      ['avatar'],
      req
    );
    const response = ApiResponse.success(formattedData, 'Tenant created successfully', 201);
    res.status(response.statusCode).json(response.body);
  });

  /**
   * Get all tenants.
   */
  getAllTenantUsers = asyncHandler(async (req: Request, res: Response): Promise<void> => {
    const tenants = await TenantQueries.getAllTenants();
    const formattedTenants = attachFileUrls(tenants, ['avatar'], req);
    const response = ApiResponse.success(formattedTenants, 'Tenants retrieved successfully');
    res.status(response.statusCode).json(response.body);
  });

  /**
   * Get tenant by ID.
   */
  getTenantUserById = asyncHandler(async (req: Request, res: Response): Promise<void> => {
    const id = req.params.id as string;
    const tenant = await TenantQueries.getById(id);
    if (!tenant) {
      throw new ApiError(404, 'Tenant not found');
    }
    const formattedTenant = attachFileUrls(tenant, ['avatar'], req);
    const response = ApiResponse.success(formattedTenant, 'Tenant retrieved successfully');
    res.status(response.statusCode).json(response.body);
  });

  /**
   * Get real-time tenant database provisioning status.
   */
  getTenantProvisioningStatus = asyncHandler(async (req: Request, res: Response): Promise<void> => {
    const id = req.params.id as string;
    const tenant = await TenantQueries.getById(id);
    if (!tenant) {
      throw new ApiError(404, 'Tenant not found');
    }
    const statusData = {
      id: tenant.id,
      tenantDbName: tenant.tenantDbName,
      provisioningStatus: tenant.status,
      provisioningProgress: tenant.provisioningProgress,
      totalVotersCopied: tenant.totalVotersCopied,
      currentStep: tenant.currentStep,
      currentPhase: tenant.currentPhase || 'init',
      activeTable: tenant.activeTable || null,
      processedRecords: tenant.processedRecords || 0,
      totalRecords: tenant.totalRecords || 0,
      errorMessage: tenant.errorMessage || null,
      updatedAt: tenant.updatedAt,
    };
    const response = ApiResponse.success(statusData, 'Tenant provisioning status retrieved successfully');
    res.status(response.statusCode).json(response.body);
  });

  /**
   * Update tenant profile and constituency scope.
   */
  updateTenantUser = asyncHandler(async (req: Request, res: Response): Promise<void> => {
    const id = req.params.id as string;
    const { name, email, mobile, organizationName, pcIds, acIds, tenantRoleId, avatar } = req.body;

    if (!name || !email || !mobile || !organizationName) {
      throw new ApiError(400, 'Name, email, mobile, and organization name are required');
    }

    const existing = await TenantQueries.getById(id);
    if (!existing) {
      throw new ApiError(404, 'Tenant not found');
    }

    const effectiveName = name !== undefined ? name.trim() : existing.name;
    const effectiveEmail = email !== undefined ? email.trim().toLowerCase() : existing.email;
    const effectiveMobile = mobile !== undefined ? mobile.trim() : existing.mobile;
    const effectiveOrgName = organizationName !== undefined ? organizationName.trim() : existing.organizationName;

    if (!effectiveName || !effectiveEmail || !effectiveOrgName) {
      throw new ApiError(400, 'Name, email, and organization name are required');
    }

    let newAcIds: string[] = acIds !== undefined ? (Array.isArray(acIds) ? [...acIds] : []) : (existing.acIds || []);
    let newPcIds: string[] = pcIds !== undefined ? (Array.isArray(pcIds) ? [...pcIds] : []) : (existing.pcIds || []);

    // Auto-resolve ACs from PCs or vice-versa
    if (newAcIds.length === 0 && newPcIds.length > 0) {
      const acRes = await masterQuery(
        'SELECT id FROM assembly_constituencies WHERE pc_id = ANY($1)',
        [newPcIds]
      );
      newAcIds = acRes.rows.map((r: any) => r.id);
    } else if (newPcIds.length === 0 && newAcIds.length > 0) {
      const pcRes = await masterQuery(
        'SELECT DISTINCT pc_id FROM assembly_constituencies WHERE id = ANY($1) AND pc_id IS NOT NULL',
        [newAcIds]
      );
      newPcIds = pcRes.rows.map((r: any) => r.pc_id);
    }

    let addedAcIds: string[] = [];
    let removedAcIds: string[] = [];

    if (existing.tenantDbName && (acIds !== undefined || pcIds !== undefined)) {
      let tenantPool: Pool | null = null;
      try {
        tenantPool = getTenantDbPool(existing.tenantDbName);
        const existingAcRes = await tenantPool.query('SELECT id FROM assembly_constituencies');
        const tenantAcIds: string[] = existingAcRes.rows.map((r: any) => r.id);

        const tenantVoterAcRes = await tenantPool.query('SELECT DISTINCT ac_id FROM voters');
        const tenantAcWithVoters: string[] = tenantVoterAcRes.rows.map((r: any) => r.ac_id);

        addedAcIds = newAcIds.filter((ac) => !tenantAcIds.includes(ac) || !tenantAcWithVoters.includes(ac));
        removedAcIds = tenantAcIds.filter((ac) => !newAcIds.includes(ac));
      } catch {
        const existingAcIds: string[] = Array.isArray(existing.acIds) ? existing.acIds : [];
        addedAcIds = newAcIds.filter((ac) => !existingAcIds.includes(ac));
        removedAcIds = existingAcIds.filter((ac) => !newAcIds.includes(ac));
      } finally {
        if (tenantPool) {
          await tenantPool.end().catch(() => { });
        }
      }
    }

    const updated = await TenantQueries.updateTenant(id, {
      name: effectiveName,
      email: effectiveEmail,
      mobile: effectiveMobile,
      organizationName: effectiveOrgName,
      pcIds: newPcIds,
      acIds: newAcIds,
      tenantRoleId: tenantRoleId !== undefined ? tenantRoleId : existing.tenantRoleId,
      avatar: avatar ?? null,
    });

    if (existing.tenantDbName && (removedAcIds.length > 0 || addedAcIds.length > 0)) {
      (async () => {
        if (removedAcIds.length > 0) {
          logger.info(`[TenantController] ${removedAcIds.length} AC(s) removed for tenant '${id}' — purging scoped data...`);
          await tenantProvisioningService.removeAcVoters(id, existing.tenantDbName, removedAcIds);
        }
        if (addedAcIds.length > 0) {
          logger.info(`[TenantController] ${addedAcIds.length} new AC(s) added for tenant '${id}' — triggering incremental voter sync...`);
          await tenantProvisioningService.syncNewAcVoters(id, existing.tenantDbName, addedAcIds, newPcIds);
        }
      })().catch((err) => {
        logger.error(`[TenantController] Incremental voter sync/purge error for tenant '${id}':`, err);
      });
    }

    const formatted = attachFileUrls(updated, ['avatar'], req);
    const response = ApiResponse.success(formatted, 'Tenant updated successfully');
    res.status(response.statusCode).json(response.body);
  });

  /**
   * Update tenant account status (active, suspended, failed).
   */
  updateTenantStatus = asyncHandler(async (req: Request, res: Response): Promise<void> => {
    const id = req.params.id as string;
    const { status } = req.body;

    const validStatuses = ['pending', 'provisioning', 'active', 'failed', 'suspended'];
    if (!status || !validStatuses.includes(status)) {
      throw new ApiError(400, `Valid status (${validStatuses.join(', ')}) is required`);
    }

    const existing = await TenantQueries.getById(id);
    if (!existing) {
      throw new ApiError(404, 'Tenant not found');
    }

    const updated = await TenantQueries.updateTenantStatus(id, status);
    const formatted = attachFileUrls(updated, ['avatar'], req);
    const response = ApiResponse.success(formatted, `Tenant status updated to ${status}`);
    res.status(response.statusCode).json(response.body);
  });

  /**
   * Delete a tenant account.
   */
  deleteTenantUser = asyncHandler(async (req: Request, res: Response): Promise<void> => {
    const id = req.params.id as string;
    const existing = await TenantQueries.getById(id);
    if (!existing) {
      throw new ApiError(404, 'Tenant not found');
    }

    await TenantQueries.deleteTenant(id);
    const response = ApiResponse.success({ id }, 'Tenant account deleted successfully');
    res.status(response.statusCode).json(response.body);
  });
}

export const tenantController = new TenantController();
