import { StyleSheet, Dimensions } from 'react-native';
import { Theme } from '../../constants/theme';
import { FontFamily } from '../../utils/typography';
import { rfValue } from '../../utils/responsive';

const { width: SCREEN_WIDTH } = Dimensions.get('window');
const CARD_WIDTH = (SCREEN_WIDTH - 40 - 22) / 3;

export const getStyles = (theme: Theme) =>
  StyleSheet.create({
    container: {
      width: '100%',
    },
    textareaInput: {
      minHeight: 200,
      textAlignVertical: 'top',
    },
    fieldLabel: {
      fontFamily: FontFamily.medium,
      fontSize: rfValue(13),
      color: theme.colors.textSecondary,
      marginBottom: theme.space.xs,
      letterSpacing: 0.2,
    },
    segmentContainer: {
      flexDirection: 'row',
      backgroundColor: theme.colors.inputBackground,
      borderRadius: 12,
      padding: 4,
      width: '100%',
      height: 52,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    segmentContainerDisabled: {
      opacity: 0.6,
    },
    segmentWrapper: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
    },
    segmentButton: {
      flex: 1,
      borderRadius: 10,
      height: '100%',
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 4,
    },
    segmentIcon: {
      marginBottom: 0,
    },
    segmentIconWithLabel: {
      marginBottom: 2,
    },
    segmentLabel: {
      fontSize: rfValue(12),
      letterSpacing: 0.3,
    },
    segmentDivider: {
      height: '70%',
      width: 1,
      backgroundColor: theme.colors.border,
      marginHorizontal: 2,
    },
    selectBox: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: theme.colors.surface,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.colors.border,
      paddingHorizontal: 16,
      height: 50,
    },
    selectRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    optionRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    modalIconContainer: {
      width: 36,
      height: 36,
      borderRadius: 18,
      alignItems: 'center',
      justifyContent: 'center',
    },
    dateRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    selectBoxError: {
      borderColor: theme.colors.error,
      backgroundColor: theme.colors.error + '05',
    },
    selectText: {
      fontFamily: FontFamily.medium,
      fontSize: rfValue(13.5),
      color: theme.colors.text,
      includeFontPadding: false,
      textAlignVertical: 'center',
    },
    placeholder: {
      color: theme.colors.textSecondary + '99',
    },
    checkboxContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginVertical: 4,
    },
    checkboxBox: {
      width: 20,
      height: 20,
      borderRadius: 5,
      borderWidth: 1.5,
      borderColor: theme.colors.border,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: theme.space.sm,
    },
    checkboxActive: {
      backgroundColor: theme.colors.primary,
      borderColor: theme.colors.primary,
    },
    checkboxLabel: {
      fontFamily: FontFamily.body,
      fontSize: rfValue(15),
      color: theme.colors.text,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.4)',
      justifyContent: 'center',
      alignItems: 'center',
      padding: 24,
    },
    modalContent: {
      backgroundColor: theme.colors.surface,
      borderRadius: 16,
      paddingTop: 16,
      paddingBottom: 16,
      width: '100%',
      maxHeight: '70%',
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    modalHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 20,
      paddingBottom: 12,
    },
    modalTitle: {
      fontFamily: FontFamily.heading,
      fontSize: rfValue(16),
      color: theme.colors.text,
    },
    searchBarContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.colors.inputBackground,
      borderWidth: 1,
      borderColor: theme.colors.border,
      borderRadius: 10,
      marginHorizontal: 16,
      marginBottom: 12,
      paddingHorizontal: 12,
      height: 44,
    },
    searchInput: {
      flex: 1,
      marginLeft: 8,
      fontFamily: FontFamily.body,
      fontSize: rfValue(13.5),
      color: theme.colors.text,
      paddingVertical: 0,
    },
    optionItem: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 12,
      paddingHorizontal: 16,
      borderRadius: 0,
      marginVertical: 2,
    },
    activeOptionItem: {
      backgroundColor: theme.colors.primary + '0A',
    },
    optionText: {
      fontFamily: FontFamily.body,
      fontSize: rfValue(14.5),
      color: theme.colors.text,
    },
    activeOptionText: {
      fontFamily: FontFamily.medium,
      color: theme.colors.primary,
    },
    errorText: {
      fontFamily: FontFamily.body,
      fontSize: rfValue(12),
      color: theme.colors.error,
      marginTop: theme.space.xs,
    },
    formGroupCard: {
      backgroundColor: theme.colors.surface,
      borderRadius: 16,
      padding: 16,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    formGroupCardLabel: {
      fontSize: rfValue(13.5),
      fontFamily: FontFamily.bodyBold,
      color: theme.colors.text,
      marginBottom: 10,
      letterSpacing: 0.3,
    },
    uploadBox: {
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: 1.2,
      borderColor: theme.colors.border,
      borderStyle: 'dashed',
      borderRadius: 12,
      padding: 16,
      backgroundColor: theme.colors.surface,
    },
    uploadBoxActive: {
      borderColor: theme.colors.primary,
      backgroundColor: theme.colors.primary + '08',
    },
    uploadTextContainer: {
      marginLeft: 12,
      flex: 1,
    },
    uploadTitle: {
      fontFamily: FontFamily.medium,
      fontSize: rfValue(13),
      color: theme.colors.text,
    },
    uploadSubtitle: {
      fontFamily: FontFamily.body,
      fontSize: rfValue(11),
      color: theme.colors.textSecondary,
      marginTop: 2,
    },
    formMediaCard: {
      width: CARD_WIDTH,
      height: CARD_WIDTH,
      borderRadius: 12,
      overflow: 'hidden',
      backgroundColor: theme.colors.inputBackground,
      position: 'relative',
      borderWidth: 1,
      borderColor: theme.colors.border + '15',
    },
    formMediaThumb: {
      width: '100%',
      height: '100%',
    },
    formMediaIconBadge: {
      position: 'absolute',
      top: '50%',
      left: '50%',
      transform: [{ translateX: -15 }, { translateY: -15 }],
      backgroundColor: 'rgba(0,0,0,0.5)',
      borderRadius: 15,
      width: 30,
      height: 30,
      alignItems: 'center',
      justifyContent: 'center',
    },
    deleteMediaItemBtn: {
      position: 'absolute',
      top: 6,
      right: 6,
      backgroundColor: 'rgba(0, 0, 0, 0.55)',
      borderRadius: 25,
      width: 25,
      height: 25,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.3)',
    },
  });
